# Generated by Django 4.2 on 2025-12-14 05:33

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('phlebotomist', 'phlebotomist'), ('business_owner', 'business_owner')], max_length=20)),
                ('account_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=30, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('info', models.TextField()),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('appointment_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('start_date_start_time', models.TimeField()),
                ('start_date_end_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_date_start_time', models.TimeField()),
                ('end_date_end_time', models.TimeField()),
                ('hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField()),
                ('current_medication', models.TextField(blank=True, null=True)),
                ('prescription', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='prescription')),
                ('known_allergies', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.JSONField(default=list)),
                ('special_request', models.CharField(blank=True, max_length=1024, null=True)),
                ('email_notification_enable', models.BooleanField(default=False)),
                ('terms_and_condition_agreement', models.BooleanField(default=False)),
                ('agreement', models.BooleanField(default=False)),
                ('initial_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('tax_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('payment_status', models.BooleanField(default=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportUserModel',
            fields=[
                ('reported_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', db_index=True, length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('reported_reason', models.CharField(max_length=255)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('case_status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('ai_flag_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_flagged_responsed', models.BooleanField(default=False)),
                ('ai_flag', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=255, null=True)),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reported_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhlebotomistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('speciality', models.CharField(blank=True, max_length=100, null=True)),
                ('license_document_upload', models.FileField(blank=True, null=True, upload_to='phlebotomist_licenses/')),
                ('identification_upload', models.FileField(blank=True, null=True, upload_to='phlebotomist_identifications/')),
                ('work_preferable', models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=10, null=True)),
                ('service_area', models.CharField(blank=True, max_length=255, null=True)),
                ('weekly_schedule', models.JSONField(blank=True, default=list, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phlebotomist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('info', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=2000, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('business_license_document', models.FileField(blank=True, null=True, upload_to='business_licenses/')),
                ('hourly_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_job_types', models.JSONField(blank=True, default=list, null=True)),
                ('work_time', models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=20, null=True)),
                ('weekly_schedule', models.JSONField(blank=True, default=list, null=True)),
                ('digital_sign', models.CharField(blank=True, max_length=255, null=True)),
                ('agree', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
