# Generated by Django 4.2 on 2025-12-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedassignedjob',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
