# Generated by Django 4.2 on 2025-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owner', '0002_completedassignedjob_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedassignedjob',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
