# Generated by Django 4.2 on 2025-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owner', '0003_acceptedassignedjob_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedassignedjob',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
