# Generated by Django 4.2 on 2025-12-14 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('ai_approval_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('inappropriate', 'Inappropriate')], default='pending', max_length=50)),
                ('admin_decision', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('delete', 'Delete'), ('suspend', 'Suspend')], default='pending', max_length=50)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InappropriateMessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_job', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_reason', models.TextField(blank=True, null=True)),
                ('reported_title', models.CharField(blank=True, max_length=255, null=True)),
                ('message_content', models.TextField()),
                ('admin_decision', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('delete', 'Delete'), ('suspend', 'Suspend')], default='pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inappropriate_reports', to='message.message')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inappropriate_messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inappropriate_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
